- name: install nginx
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed

- name: install rpm
  ansible.builtin.dnf:
    name: "@redis:remi-6.2"
    state: installed

- name: replace
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: 127.0.0.1
    replace: 0.0.0.0

- name: restart redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
