- name: install nginx
  yum:
    name: nginx
    state: installed

- name: remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download frontend
  ansible.builtin.unarchive:
    src: curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /tmp/frontend.zip
     cd /usr/share/nginx/html
    remote_src: yes
