- name: cofig repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

#- name: install rabbitmq
#  ansible.builtin.yum:
#    name:
#      - rabbitmq-server
#      - erlang
#    state: installed
#
#- name: start rabbitmq
#  ansible.builtin.systemd:
#    name: rabbitmq-server
#    state: restarted
#    enabled: yes
#
#- name: set user
#  ansible.builtin.

