- name: copy the repo file
  template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install filebeat
  yum:
    name: filebeat
    state: installed
    enabled: yes
  #when: filebeat

- name: restart elastic search
  systemd:
    name: filebeat
    state: restarted