- name: download alertmanager
  unarchive:
    src: "{{ alertmanager_url }}"
    dest: /opt
    remote_src: true

- name: copy alertmanager service file
  template:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: start service
  systemd:
    name: alertmanager
    state: restarted
    enabled: true
    daemon-reload: true
