- name: create user
  ansible.builtin.user:
    name: app

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create a directory
  ansible.builtin.file:
    path: /app

- name: download file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/cart.zip
    dest: /app
    remote_src: yes








