- name: copy repo
  template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: download the grafana
  yum:
    name: grafana
    state: installed

- name: start grafana
  systemd:
    name: grafana
    state: restarted
    enabled: yes