- name: copy prometheus config file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
    remote_src: true

- name: copy the alert rules
  template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}
  loop: "{{ alert_files }}"

- name: copy the service alert rules
  template:
    src: service-down-alerts.yml
    dest: /opt/prometheus/service-down-alerts.yml

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: copy alertmanager config file
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager-0.27.0-rc.0.linux-amd64/alertmanager.yml

- name: restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
