- name: create user
  ansible.builtin.user:
    name: roboshop

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create a directory
  ansible.builtin.file:
    path: /app
    state: directory

## Download from S3
#- name: download file
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

## Download from Nexus
- name: download file
  ansible.builtin.unarchive:
    src: http://{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.user', region='us-east-1') }}:{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.pass', region='us-east-1') }}@nexus.roboz.online:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes








