- name: set host name
  shell:
    set-hostname {{component}}

- name: error 1
  shell:
    cd /etc/yum.repos.d/

- name: error 2
  shell:
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*

- name: error 3
  shell:
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

- name: install node exporter
  import_role:
    name: prometheus
    tasks_from: exporter
  when: node_exporter

- name: install filebeat
  import_role:
    name: elk
    tasks_from: filebeat
  when: filebeat

