- name: nodejs repo disable
  ansible.builtin.shell:
    dnf module disable nodejs -y

- name: nodejs enable
  ansible.builtin.shell:
    dnf module enable nodejs:18 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: import tasks prereq
  ansible.builtin.import_tasks:
    file: app_prereq.yml

#- name: npm dependencies
#  community.general.npm:
#    path: /app

#- name: npm
#  shell: npm install
#  args:
#    chdir: /app

- name: import schema tasks
  ansible.builtin.import_tasks:
    file: schema_setup.yml
  when: schema_type is defined

- name: import systemd task
  ansible.builtin.import_tasks:
    file: systemd_setup.yml





