- name: copy service file
  ansible.builtin.copy:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: restart service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: true
    daemon-reload: true