prometheus_server: false
node_exporter: false
grafana: false
exporter_url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
exporter_dir: "{{ exporter_url | split('/') | last | regex_replace('.tar.gz', '') }}"