groups:
  - name: roboshop
    rules:
      - alert: ServerDown
        expr: up < 1
        for: 30sec
        labels:
          severity: critical
        annotations:
          summary: server down
