route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: "email"
    email_configs:
      - to: friendscreations634@gmail.com
        from: friendscreations634@gmail.com
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: "{{user}}"
        auth_password: "{{pass}}"
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']





