groups:
  - name: roboshop
    rules:
    {% for component in components %}

    - alert: Service down alert - {{ component }} service
      expr: node_systemd_unit_state{exported_name="{{ component }}.service",state="active"} < 1
      for: 30s
      labels:
        severity: critical
        appName: { { component } }
      annotations:
        summary: service down on some server - service name - {{component}}.service

    {% endfor %}


